spring:
	application:
		name:EUREKA-SERVER
server:
	port:8761

eureka:
	client:
		registerWithEureka:false
		fetchRegistry:false

documentation: 
  baseurl: http://localhost
  swagger: 
    services:   
      - 
        name: MOBILE-SERVICE
        url: ${documentation.baseurl}:8001/v2/api-docs?group=service1
        version: 2.0
      - 
        name: <Service 2>
        url: ${documentation.baseurl}:8002/v2/api-docs?group=service2
        version: 2.0